function [s] = statistics()
    s = {

% Removed due to generating NaN when values are 0
%         struct( ...
%             'name', 'harmonic_mean', ...
%             'function', @harmmean ...
%         )        
        
        struct( ...
            'name', 'trimmedMean(90%)', ...
            'function', @(a) trimmean(a, 10) ...
        )
        
        struct( ...
            'name', 'mean', ...
            'function', @nanmean ...
        )   

        struct( ...
            'name', 'median', ...
            'function', @nanmedian ...
        )             

        struct( ...
            'name', 'kurtosis', ...
            'function', @kurtosis ...
        )   

        struct( ...
            'name', 'skewness', ...
            'function', @skewness ...
        )   

        struct( ...
            'name', 'standardDeviation', ...
            'function', @nanstd ...
        )

        struct( ...
            'name', 'variance', ...
            'function', @nanvar ...
        )        

        struct( ...
            'name', 'range', ...
            'function', @range ...
        )
        
        struct( ...
            'name', 'max', ...
            'function', @nanmax ...
        )
        
        struct( ...
            'name', 'min', ...
            'function', @nanmin ...
        )
        
        struct( ...
            'name', 'interquartileRange', ...
            'function', @iqr ...
        )
                
        struct( ...
            'name', 'meanAbsoluteDeviation', ...
            'function', @mad ...
        )
               
    };


end

