function [c] = configuration()

    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', 'Number of Connected Regions' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', '' ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'connectedRegions' ...
        ) 
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'connectivity', ...
            'required', true, ...
            'default', 18 ...
        )         
    };
end