function [ c ] = levelAndWindowSettings()
%LEVELANDWINDOWSETTINGS Summary of this function goes here
%   Detailed explanation goes here

    c = struct();

    c.ctAbdomen = struct(...
        'window', 350, ...
        'level', 40 ...
    );

    c.ctPelvis = struct(...
        'window', 350, ...
        'level', 40 ...
    );

    c.ctBone = struct(...
        'window', 2500, ...
        'level', 480 ...
    );

    c.ctBrain = struct(...
        'window', 80, ...
        'level', 40 ...
    );

    c.ctCta = struct(...
        'window', 650, ...
        'level', 50 ...
    );

    c.ctKidney = struct(...
        'window', 700, ...
        'level', 50 ...
    );

    c.ctLiver = struct(...
        'window', 120, ...
        'level', 70 ...
    );

    c.ctLung = struct(...
        'window', 1500, ...
        'level', -500 ...
    );

    c.ctMediastinum = struct(...
        'window', 4000, ...
        'level', 40 ...
    );

    c.ctChest = struct(...
        'window', 4000, ...
        'level', 40 ...
    );

    c.ctMyelogram = struct(...
        'window', 880, ...
        'level', 110 ...
    );

    c.ctNeck = struct(...
        'window', 350, ...
        'level', 20 ...
    );

    c.ctSinus = struct(...
        'window', 2000, ...
        'level', 100 ...
    );

    c.ctStroke = struct(...
        'window', 50, ...
        'level', 40 ...
    );

    c.ctSubdural = struct(...
        'window', 350, ...
        'level', 90 ...
    );

    c.custom = struct(...
        'window', 0, ...
        'level', 0 ...
    );
end

