function [c] = configuration() 
    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', '2D Pipeline' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', '' ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'features2D' ...
        ) 
        struct( ...
            'name', 'category', ...
            'required', true, ...
            'default', 'Dimension2' ...
        ) 
        struct( ...
            'name', 'intensityVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'infoVOI', ...
            'required', true, ...
            'internal', true ...
        ) 
        struct( ...
            'name', 'organ', ...
            'required', true, ...
            'default', 'lung' ...
        )   
        struct( ...
            'name', 'largestSlice', ...
            'required', true, ...
            'default', true ...
        )
        struct( ...
            'name', 'largestSliceName', ...
            'required', true, ...
            'default', 'largestSlice' ...
        )
        struct( ...
            'name', 'middleSlice', ...
            'required', true, ...
            'default', true ...
        )
        struct( ...
            'name', 'middleSliceName', ...
            'required', true, ...
            'default', 'middleSlice' ...
        )        
        struct( ...
            'name', 'separator', ...
            'required', true, ...
            'default', '.' ...
        ) 
        struct( ...
            'name', 'glcmMinAndMaxIntensity', ...
            'required', true, ...
            'default', '' ...
        )
        struct( ...
            'name', 'glcmNumLevels', ...
            'required', true, ...
            'default', 8 ...
        )
        struct( ...
            'name', 'glcmSymmetric', ...
            'required', true, ...
            'default', false ...
        )
    };
end
