function [ out ] = run( inputs )
%RUN Summary of this function goes here
%   Detailed explanation goes here

    %% Initialization
    featureRootName = inputs.featureRootName;
    out = struct('featureRootName', featureRootName);
    
    %% Extract version values
    gitBranch = inputs.gitBranch;
    if isnan(gitBranch)
        gitBranch = 'none';
    end
    
    gitHash = inputs.gitHash;
    if isnan(gitHash)
        gitHash = 'none';
    end
    
    dockerTag = inputs.dockerTag;
    if isnan(dockerTag)
        dockerTag = 'none';
    end
    
    buildDate = inputs.buildDate;
    if isnan(buildDate)
        buildDate = 'none';
    end    
    
    runDate = inputs.runDate;
    if isnan(runDate)
        runDate = 'none';
    end        
    %% Return version values
    out.output = { ... 
        struct(...
        'name', 'gitBranch',...
        'value', gitBranch ...
        ) ...
        struct(...
        'name', 'gitHash',...
        'value', gitHash ...
        ) ...
        struct(...
        'name', 'dockerTag',...
        'value', dockerTag ...
        ) ...
        struct(...
        'name', 'buildDate',...
        'value', buildDate ...
        ) ...     
        struct(...
        'name', 'runDate',...
        'value', runDate ...
        ) ...         
    };
end

