function [c] = configuration() 

    references = {
    };

    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', 'Law''s Texture Features' ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'laws' ...
        ) 
        struct( ...
            'name', 'category', ...
            'required', true, ...
            'default', 'texture' ...
        ) 
        struct( ...
            'name', 'samplePoints', ...
            'required', true, ...
            'default', 5 ...
        )
        struct( ...
            'name', 'resolutions', ...
            'required', true, ...
            'default', '1,1.5,2' ...
        )
        struct( ...
            'name', 'intensityVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'infoVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'parallelization', ...
            'required', true, ...
            'internal', true, ...
            'default', false ...
        )
    };
end