function [c] = configuration() 

    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', 'Sigmoid Edge Fitting' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', '' ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'edgeSigmoidFitting' ...
        ) 
        struct( ...
            'name', 'normalLength', ...
            'required', true, ...
            'default', 5 ...
        ) 
        struct( ...
            'name', 'numberOfNormals', ...
            'required', true, ...
            'default', 1200 ...
        ) 
        struct( ...
            'name', 'numberOfSamplingPoints', ...
            'required', true, ...
            'default', 21 ...
        )
        struct( ...
            'name', 'intensityVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'infoVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'parallelization', ...
            'required', true, ...
            'internal', true, ...
            'default', false ...
        )
    };
end