function [c] = configuration() 
    c.configArray = {
        struct( ...
            'name', 'preProcessingName', ...
            'value', 'Fill Holes' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', '' ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
    };
end