function [c] = configuration() 

    references = {
        struct( ...
        'type', 'article', ...
        'fields', struct( ...
            'author', {'Zayed, Nourhan and Elnemr, Heba A.'}, ...
            'title', 'Statistical Analysis of Haralick Texture Features to Discriminate Lung Abnormalities', ...
            'journal', 'Journal of Biomedical Imaging', ...
            'issue_date', 'January 2015', ...
            'volume', '2015', ...
            'month', 'jan', ...
            'year', '2015', ...
            'issn', '1676-4188', ...
            'pages', '12:12--12:12', ...
            'articleno', '12', ...
            'numpages', '1', ...
            'url', 'http://dx.doi.org/10.1155/2015/267807', ...
            'doi', '10.1155/2015/267807', ...
            'acmid', '2929799', ...
            'publisher', 'Hindawi Publishing Corp.', ...
            'address', 'New York, NY, United States' ...
            ) ...
        ), ...
        struct( ...
        'type', 'article', ...
        'fields', struct( ...
            'author', {'R. M. Haralick and K. Shanmugam and I. Dinstein'}, ...
            'title', 'Textural Features for Image Classification', ...
            'journal', 'IEEE Transactions on Systems, Man, and Cybernetics', ...
            'volume', 'SMC-3', ...
            'year', '1973', ...
            'issn', '0018-9472', ...
            'pages', '610-621', ...
            'number', '6', ...
            'month', 'Nov', ...
            'doi', '10.1109/TSMC.1973.4309314' ...
            ) ...
        )
    };

    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', 'Haralick''s features' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', references ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'glcm' ...
        ) 
        struct( ...
            'name', 'category', ...
            'required', true, ...
            'default', 'texture' ...
        ) 
        struct( ...
            'name', 'distance', ...
            'required', true, ...
            'default', '1,2,3' ...
        )
        struct( ...
            'name', 'grayLevels', ...
            'required', true, ...
            'default', 256 ...
        )        
        struct( ...
            'name', 'intensityVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'infoVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'customIntensity', ...
            'required', false, ...
            'default', true ...
        )        
        struct( ...
            'name', 'minIntensity', ...
            'required', false, ...
            'default', -1000 ...
        )
        struct( ...
            'name', 'maxIntensity', ...
            'required', false, ...
            'default', 3096 ...
        )
        struct( ...
            'name', 'symmetric', ...
            'required', false, ...
            'default', true ...
        )
        struct( ...
            'name', 'parallelization', ...
            'required', true, ...
            'internal', true, ...
            'default', false ...
        )
    };
end