function [c] = configuration() 
        
    reference = {
        struct( ...
        'type', 'article', ...
        'fields', struct( ...
            'author', {'Mishchenko, Yuriy'}, ...
            'title', 'A fast algorithm for computation of discrete Euclidean distance transform in three or more dimensions on vector processing architectures', ...
            'journal', 'Signal, Image and Video Processing', ...
            'volume', '9', ...
            'issue', '1', ...
            'year', '2015', ...
            'issn', '1863-1711', ...
            'pages', '19-27', ...
            'doi', '10.1007/s11760-012-0419-9' ...
            ) ...
        ), ...
    };

    c.configArray = {
        struct( ...
            'name', 'preProcessingName', ...
            'value', 'Create Peri-Tumoral Region' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', reference ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'infoVOI', ...
            'required', true, ...
            'internal', true ...
        ) 
        struct( ...
            'name', 'operation', ...
            'required', true, ...
            'default', 'exclude' ...
        ) 
        struct( ...
            'name', 'distance', ...
            'required', true, ...
            'default', 10 ...
        )
    };
end
