function [c] = configuration()

    references = {
        struct( ...
        'type', 'article', ...
        'fields', struct( ...
            'author', {'Mildenberger, Peter and Eichelberg, Marco and Martin, Eric'}, ...
            'title', 'Introduction to the DICOM standard', ...
            'journal', 'European Radiology', ...
            'year', '2002', ...
            'volume', '12', ...
            'number', '4', ...
            'pages', '920--927',...
            'abstract', ['Digital Imaging and Communication in Medicine'...
                         '(DICOM) has become one of the most popular' ...
                         ' standards in medicine. In the beginning, ' ...
                         ' DICOM was used for communication of image'...
                         ' data between different systems. Actual' ...
                         ' developments of the standardisation enables' ...
                         ' increasingly more DICOM-based services for ' ...
                         ' the integration of modalities and information' ...
                         ' systems (e.g. RIS, PACS). In this article' ...
                         ' a review of the historical background, the' ...
                         ' technological concept, the organizational' ...
                         ' structure and current developments is given.'], ...
            'issn', '1432-1084', ...
            'doi', '10.1007/s003300101100', ...
            'url', 'http://dx.doi.org/10.1007/s003300101100' ...
            ) ...
        )...
    };

    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', 'Patient Information' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', references ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'aa_info' ...
        ) 
        struct( ...
            'name', 'segmentationInfo', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'infoVOI', ...
            'required', true, ...
            'internal', true ...
        )
    };
end