function [c] = configuration() 
    c.configArray = {
        struct( ...
            'name', 'preProcessingName', ...
            'value', 'Topology Preservation' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', '' ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'infoVOI', ...
            'required', true, ...
            'internal', true ...
        ) 
        struct( ...
            'name', 'radius', ...
            'required', true ...
        ) 
    };
end