function [c] = configuration() 
    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', 'Intensity Histogram' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', '' ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'intensity' ...
        ) 
        struct( ...
            'name', 'intensityVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
    };
end