function [c] = configuration() 
    
    references = {
        struct( ...
        'type', 'book', ...
        'fields', struct( ...
            'author', {'Whitehouse, D.J.'}, ...
            'title', 'Surfaces and their Measurement', ...
            'year', '2004', ...
            'isbn', '9780080518237', ...
            'url', 'https://books.google.com/books?id=3laae9sWgR0C', ...
            'publisher', 'Elsevier Science' ...
            ) ...
        ), ...
        struct( ...
        'type', 'book', ...
        'fields', struct( ...
            'author', {'Black, J.T. and Kohser, R.A.'}, ...
            'title', 'DeGarmo''s Materials and Processes in Manufacturing', ...
            'year', '2011', ...
            'lccn', '2011294340', ...
            'isbn', '9780470924679', ...
            'url', 'https://books.google.com/books?id=8roLjMs08zoC', ...
            'publisher', 'Wiley' ...
            ) ...
        ) ...
    };

    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', 'Local Roughness' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', references ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'roughness' ...
        )
        struct( ...
            'name', 'patchDistance', ...
            'required', true, ...
            'default', 5 ...
        )
        struct( ...
            'name', 'featureSize', ...
            'required', true, ...
            'default', '1,2,3,4,5' ...
        ) 
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'infoVOI', ...
            'required', true, ...
            'internal', true ...
        ) 
    };
end