function [c] = configuration() 
    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', 'Preprocess Modules' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', '' ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'preprocessModules' ...
        ) 
        struct( ...
            'name', 'category', ...
            'required', true, ...
            'default', 'meta' ...
        ) 
        struct( ...
            'name', 'separator', ...
            'required', false, ...
            'default', '|' ...
        )         
        struct( ...
            'name', 'preprocessingToRun', ...
            'required', true, ...
            'internal', true ...
        )
    };
end