function [c] = configuration() 

    c.configArray = {
        struct( ...
            'name', 'featureName', ...
            'value', 'Local Volume Integral Invariant' ...
        )
        struct( ...
            'name', 'reference', ...
            'value', '' ...
        )
        struct( ...
            'name', 'functionToRun', ...
            'value', 'run' ...
        )
    };

    c.inputArray = { 
        struct( ...
            'name', 'featureRootName', ...
            'required', true, ...
            'default', 'lvii' ...
        )
        struct( ...
            'name', 'sphereRadius', ...
            'required', true, ...
            'default', '1,2,3,4,5' ...
        )         
        struct( ...
            'name', 'segmentationVOI', ...
            'required', true, ...
            'internal', true ...
        )
        struct( ...
            'name', 'infoVOI', ...
            'required', true, ...
            'internal', true ...
        ) 
    };
end